version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/install:
          filters:
            branches:
              only: 
                - main
                - develop
      - cypress/run:
          filters:
            branches:
              only:
                - main
                - develop
          requires:
            - cypress/install
          record: true
          parallel: true
          parallelism: 2
          group: 2 machines
